name: gabpharma_patient
description: Application mobile Patient de Gab'Pharma.
publish_to: none
version: 0.1.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: 4.11.0
  firebase_messaging: 16.4.0
  flutter_secure_storage: ^9.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/icon/

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/icon/icon.png"
  adaptive_icon_background: "#006A35"
  adaptive_icon_foreground: "assets/icon/icon_foreground.png"
  min_sdk_android: 21
